-- =============================================================================
-- BRONZE LAYER
-- Database: MOVIE_PROJECT_DB
-- Purpose: Storage integrations, file formats, stages, and table DDL
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

-- =============================================================================
-- SCHEMAS
-- =============================================================================

CREATE DATABASE IF NOT EXISTS MOVIE_PROJECT_DB;
CREATE SCHEMA IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API;
CREATE SCHEMA IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_IMDB;
CREATE SCHEMA IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2;
CREATE SCHEMA IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS;

-- =============================================================================
-- STORAGE INTEGRATIONS (AWS S3)
-- =============================================================================
-- Your S3 Buckets & Roles:
--   <YOUR_IMDB_BUCKET>         → path: S3/          → role: <YOUR_IMDB_ROLE>
--   <YOUR_KAGGLE_BUCKET>       → path: archive/     → role: <YOUR_KAGGLE_ROLE>
--   <YOUR_MOVIELENS_BUCKET>    → path: ml-32m/      → role: <YOUR_MOVIELENS_ROLE>
--   (Netflix: internal stage upload only)

CREATE OR REPLACE STORAGE INTEGRATION movie_s3_imdb_integration
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<YOUR_AWS_ACCOUNT_ID>:role/<YOUR_IMDB_ROLE>'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<YOUR_IMDB_BUCKET>/S3/');

CREATE OR REPLACE STORAGE INTEGRATION movie_s3_kaggle_integration
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<YOUR_AWS_ACCOUNT_ID>:role/<YOUR_KAGGLE_ROLE>'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<YOUR_KAGGLE_BUCKET>/archive/');

CREATE OR REPLACE STORAGE INTEGRATION movie_s3_movielens_integration
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<YOUR_AWS_ACCOUNT_ID>:role/<YOUR_MOVIELENS_ROLE>'
  STORAGE_ALLOWED_LOCATIONS = (
    's3://<YOUR_MOVIELENS_BUCKET>/ml-32m/',
    's3://<YOUR_MOVIELENS_BUCKET>/ml-25m/'
  );

-- Get STORAGE_AWS_IAM_USER_ARN and STORAGE_AWS_EXTERNAL_ID for AWS Trust Policy
DESC INTEGRATION movie_s3_imdb_integration;
DESC INTEGRATION movie_s3_kaggle_integration;
DESC INTEGRATION movie_s3_movielens_integration;

-- =============================================================================
-- FILE FORMATS
-- =============================================================================

CREATE OR REPLACE FILE FORMAT MOVIE_PROJECT_DB.PUBLIC.csv_format
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('', 'NULL', '\\N')
  FIELD_DELIMITER = ','
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE OR REPLACE FILE FORMAT MOVIE_PROJECT_DB.PUBLIC.tsv_format
  TYPE = 'CSV'
  FIELD_DELIMITER = '\t'
  SKIP_HEADER = 1
  NULL_IF = ('', '\\N', 'NULL')
  COMPRESSION = GZIP
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

-- =============================================================================
-- EXTERNAL STAGES
-- =============================================================================

CREATE OR REPLACE STAGE MOVIE_PROJECT_DB.BRONZE_API_IMDB.s3_stage
  URL = 's3://<YOUR_IMDB_BUCKET>/S3/'
  STORAGE_INTEGRATION = movie_s3_imdb_integration
  FILE_FORMAT = MOVIE_PROJECT_DB.PUBLIC.tsv_format;

CREATE OR REPLACE STAGE MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.s3_stage
  URL = 's3://<YOUR_KAGGLE_BUCKET>/archive/'
  STORAGE_INTEGRATION = movie_s3_kaggle_integration
  FILE_FORMAT = MOVIE_PROJECT_DB.PUBLIC.csv_format;

CREATE OR REPLACE STAGE MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.s3_stage
  URL = 's3://<YOUR_MOVIELENS_BUCKET>/ml-32m/'
  STORAGE_INTEGRATION = movie_s3_movielens_integration
  FILE_FORMAT = MOVIE_PROJECT_DB.PUBLIC.csv_format;

-- =============================================================================
-- INTERNAL STAGES (for manual CSV uploads via Snowsight)
-- =============================================================================

CREATE OR REPLACE STAGE MOVIE_PROJECT_DB.BRONZE_API.upload_stage
  FILE_FORMAT = MOVIE_PROJECT_DB.PUBLIC.csv_format;

CREATE OR REPLACE STAGE MOVIE_PROJECT_DB.BRONZE_API_IMDB.upload_stage
  FILE_FORMAT = MOVIE_PROJECT_DB.PUBLIC.tsv_format;

CREATE OR REPLACE STAGE MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.upload_stage
  FILE_FORMAT = MOVIE_PROJECT_DB.PUBLIC.csv_format;

CREATE OR REPLACE STAGE MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.upload_stage
  FILE_FORMAT = MOVIE_PROJECT_DB.PUBLIC.csv_format;

-- =============================================================================
-- TABLE DDL: BRONZE_API (Netflix)
-- =============================================================================

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API.NETFLIX (
    SHOW_ID VARCHAR,
    TYPE VARCHAR,
    TITLE VARCHAR,
    DIRECTOR VARCHAR,
    "CAST" VARCHAR,
    COUNTRY VARCHAR,
    DATE_ADDED VARCHAR,
    RELEASE_YEAR VARCHAR,
    RATING VARCHAR,
    DURATION VARCHAR,
    LISTED_IN VARCHAR,
    DESCRIPTION VARCHAR
);

-- =============================================================================
-- TABLE DDL: BRONZE_API_IMDB
-- =============================================================================

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_BASICS (
    TCONST VARCHAR,
    TITLETYPE VARCHAR,
    PRIMARYTITLE VARCHAR,
    ORIGINALTITLE VARCHAR,
    ISADULT NUMBER,
    STARTYEAR NUMBER,
    ENDYEAR VARCHAR,
    RUNTIMEMINUTES NUMBER,
    GENRES VARCHAR
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_RATINGS (
    TCONST VARCHAR,
    AVERAGERATING NUMBER(38,1),
    NUMVOTES NUMBER
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_CREW (
    TCONST VARCHAR,
    DIRECTORS VARCHAR,
    WRITERS VARCHAR
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_EPISODE (
    TCONST VARCHAR,
    PARENTTCONST VARCHAR,
    SEASONNUMBER NUMBER,
    EPISODENUMBER NUMBER
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_PRINCIPALS (
    TCONST VARCHAR,
    ORDERING NUMBER,
    NCONST VARCHAR,
    CATEGORY VARCHAR,
    JOB VARCHAR,
    CHARACTERS VARCHAR
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_AKAS (
    TITLEID VARCHAR,
    ORDERING NUMBER,
    TITLE VARCHAR,
    REGION VARCHAR,
    LANGUAGE VARCHAR,
    TYPES VARCHAR,
    ATTRIBUTES VARCHAR,
    ISOРИГINALТITLE NUMBER
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_IMDB.NAME_BASICS (
    NCONST VARCHAR,
    PRIMARYNAME VARCHAR,
    PRIMARYPROFESSION VARCHAR,
    KNOWNFORTITLES VARCHAR
);

-- =============================================================================
-- TABLE DDL: BRONZE_API_KAGGLE2
-- =============================================================================

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.MOVIES_METADATA (
    ADULT VARCHAR,
    BELONGS_TO_COLLECTION VARCHAR,
    BUDGET VARCHAR,
    GENRES VARCHAR,
    HOMEPAGE VARCHAR,
    ID VARCHAR,
    IMDB_ID VARCHAR,
    ORIGINAL_LANGUAGE VARCHAR,
    ORIGINAL_TITLE VARCHAR,
    OVERVIEW VARCHAR,
    POPULARITY VARCHAR,
    POSTER_PATH VARCHAR,
    PRODUCTION_COMPANIES VARCHAR,
    PRODUCTION_COUNTRIES VARCHAR,
    RELEASE_DATE VARCHAR,
    REVENUE VARCHAR,
    RUNTIME VARCHAR,
    SPOKEN_LANGUAGES VARCHAR,
    STATUS VARCHAR,
    TAGLINE VARCHAR,
    TITLE VARCHAR,
    VIDEO VARCHAR,
    VOTE_AVERAGE VARCHAR,
    VOTE_COUNT VARCHAR
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.CREDITS (
    CAST_COL VARCHAR,
    CREW VARCHAR,
    ID NUMBER
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.KEYWORDS (
    ID NUMBER,
    KEYWORDS VARCHAR
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.LINKS (
    MOVIEID NUMBER,
    IMDBID NUMBER,
    TMDBID NUMBER
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.LINKS_SMALL (
    MOVIEID NUMBER,
    IMDBID NUMBER,
    TMDBID NUMBER
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.RATINGS (
    USERID NUMBER,
    MOVIEID NUMBER,
    RATING NUMBER(2,1),
    TIMESTAMP NUMBER
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.RATINGS_SMALL (
    USERID NUMBER,
    MOVIEID NUMBER,
    RATING NUMBER(2,1),
    TIMESTAMP NUMBER
);

-- =============================================================================
-- TABLE DDL: BRONZE_API_MOVIE_LENS
-- =============================================================================

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.MOVIES (
    MOVIE_ID NUMBER,
    TITLE VARCHAR,
    GENRES VARCHAR
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.RATINGS (
    USER_ID NUMBER,
    MOVIE_ID NUMBER,
    RATING NUMBER(2,1),
    RATING_TIMESTAMP NUMBER
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.TAGS (
    USER_ID NUMBER,
    MOVIE_ID NUMBER,
    TAG VARCHAR,
    TAG_TIMESTAMP NUMBER
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.GENOME_SCORES (
    MOVIE_ID NUMBER,
    TAG_ID NUMBER,
    RELEVANCE FLOAT
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.GENOME_TAGS (
    TAG_ID NUMBER,
    TAG VARCHAR
);

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.LINKS (
    MOVIE_ID NUMBER,
    IMDB_ID NUMBER,
    TMDB_ID NUMBER
);
