-- =============================================================================
-- CHANGE DATA CAPTURE (CDC) & INCREMENTAL PROCESSING
-- Database: MOVIE_PROJECT_DB
-- Purpose: Streams for CDC on Bronze tables, incremental MERGE into Silver/Gold
-- Depends on: bronze_layer.sql, silver_layer.sql
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

-- =============================================================================
-- SCHEMA FOR INCREMENTAL SILVER TABLES
-- (Silver views are replaced by materialized tables for CDC support)
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS MOVIE_PROJECT_DB.SILVER;

-- =============================================================================
-- SECTION 1: STREAMS ON ALL BRONZE TABLES (Change Data Capture)
-- Streams track INSERT, UPDATE, DELETE on source tables
-- =============================================================================

-- Netflix
CREATE OR REPLACE STREAM MOVIE_PROJECT_DB.BRONZE_API.stream_netflix
  ON TABLE MOVIE_PROJECT_DB.BRONZE_API.NETFLIX
  SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on Netflix catalog data';

-- IMDB
CREATE OR REPLACE STREAM MOVIE_PROJECT_DB.BRONZE_API_IMDB.stream_title_basics
  ON TABLE MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_BASICS
  SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on IMDB title basics';

CREATE OR REPLACE STREAM MOVIE_PROJECT_DB.BRONZE_API_IMDB.stream_title_ratings
  ON TABLE MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_RATINGS
  SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on IMDB title ratings';

CREATE OR REPLACE STREAM MOVIE_PROJECT_DB.BRONZE_API_IMDB.stream_title_principals
  ON TABLE MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_PRINCIPALS
  SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on IMDB title principals (cast/crew)';

CREATE OR REPLACE STREAM MOVIE_PROJECT_DB.BRONZE_API_IMDB.stream_name_basics
  ON TABLE MOVIE_PROJECT_DB.BRONZE_API_IMDB.NAME_BASICS
  SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on IMDB person names';

CREATE OR REPLACE STREAM MOVIE_PROJECT_DB.BRONZE_API_IMDB.stream_title_crew
  ON TABLE MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_CREW
  SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on IMDB title crew';

-- Kaggle
CREATE OR REPLACE STREAM MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.stream_movies_metadata
  ON TABLE MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.MOVIES_METADATA
  SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on Kaggle movies metadata';

CREATE OR REPLACE STREAM MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.stream_credits
  ON TABLE MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.CREDITS
  SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on Kaggle credits';

CREATE OR REPLACE STREAM MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.stream_ratings
  ON TABLE MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.RATINGS
  SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on Kaggle ratings';

-- MovieLens
CREATE OR REPLACE STREAM MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.stream_movies
  ON TABLE MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.MOVIES
  SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on MovieLens movies';

CREATE OR REPLACE STREAM MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.stream_ratings
  ON TABLE MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.RATINGS
  SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on MovieLens ratings (largest table)';

CREATE OR REPLACE STREAM MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.stream_tags
  ON TABLE MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.TAGS
  SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on MovieLens user tags';

-- =============================================================================
-- SECTION 2: INCREMENTAL SILVER TABLES (MERGE from streams)
-- These replace the Silver views with materialized, incrementally-updated tables
-- =============================================================================

-- Silver: IMDB Movies (incremental)
CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.SILVER.IMDB_MOVIES_INCREMENTAL (
    TCONST VARCHAR PRIMARY KEY,
    TITLE VARCHAR,
    ORIGINALTITLE VARCHAR,
    GENRES VARCHAR,
    RELEASE_YEAR NUMBER,
    RUNTIME NUMBER,
    IMDB_RATING NUMBER(3,1),
    NUMVOTES NUMBER,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Silver: Movies Metadata (incremental)
CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.SILVER.MOVIES_METADATA_INCREMENTAL (
    MOVIE_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR,
    BUDGET NUMBER,
    REVENUE NUMBER,
    POPULARITY FLOAT,
    VOTE_AVERAGE FLOAT,
    VOTE_COUNT NUMBER,
    GENRES VARCHAR,
    PRODUCTION_COMPANIES VARCHAR,
    RUNTIME NUMBER,
    RELEASE_DATE DATE,
    RELEASE_YEAR NUMBER,
    ORIGINAL_LANGUAGE VARCHAR,
    STATUS VARCHAR,
    IMDB_ID VARCHAR,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Silver: MovieLens Aggregated Ratings (incremental)
CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.SILVER.MOVIELENS_RATINGS_INCREMENTAL (
    MOVIE_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR,
    GENRES VARCHAR,
    AVG_RATING FLOAT,
    RATING_COUNT NUMBER,
    UNIQUE_USERS NUMBER,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- SECTION 3: TASKS — INCREMENTAL MERGE (triggered only when streams have data)
-- =============================================================================

-- Task: Merge IMDB changes into Silver
CREATE OR REPLACE TASK MOVIE_PROJECT_DB.PUBLIC.task_cdc_silver_imdb
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '5 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('MOVIE_PROJECT_DB.BRONZE_API_IMDB.STREAM_TITLE_BASICS')
    OR SYSTEM$STREAM_HAS_DATA('MOVIE_PROJECT_DB.BRONZE_API_IMDB.STREAM_TITLE_RATINGS')
  COMMENT = 'Incrementally merges new/changed IMDB data into Silver layer'
AS
  MERGE INTO MOVIE_PROJECT_DB.SILVER.IMDB_MOVIES_INCREMENTAL tgt
  USING (
    SELECT
      tb.TCONST,
      tb.PRIMARYTITLE AS TITLE,
      tb.ORIGINALTITLE,
      tb.GENRES,
      tb.STARTYEAR AS RELEASE_YEAR,
      tb.RUNTIMEMINUTES AS RUNTIME,
      tr.AVERAGERATING AS IMDB_RATING,
      tr.NUMVOTES
    FROM MOVIE_PROJECT_DB.BRONZE_API_IMDB.STREAM_TITLE_BASICS tb
    JOIN MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_RATINGS tr ON tb.TCONST = tr.TCONST
    WHERE tb.TITLETYPE = 'movie'
      AND tb.STARTYEAR IS NOT NULL
      AND tr.NUMVOTES >= 100
      AND tb.METADATA$ACTION = 'INSERT'
  ) src
  ON tgt.TCONST = src.TCONST
  WHEN MATCHED THEN UPDATE SET
    tgt.TITLE = src.TITLE,
    tgt.ORIGINALTITLE = src.ORIGINALTITLE,
    tgt.GENRES = src.GENRES,
    tgt.RELEASE_YEAR = src.RELEASE_YEAR,
    tgt.RUNTIME = src.RUNTIME,
    tgt.IMDB_RATING = src.IMDB_RATING,
    tgt.NUMVOTES = src.NUMVOTES,
    tgt.LAST_UPDATED = CURRENT_TIMESTAMP()
  WHEN NOT MATCHED THEN INSERT (TCONST, TITLE, ORIGINALTITLE, GENRES, RELEASE_YEAR, RUNTIME, IMDB_RATING, NUMVOTES)
    VALUES (src.TCONST, src.TITLE, src.ORIGINALTITLE, src.GENRES, src.RELEASE_YEAR, src.RUNTIME, src.IMDB_RATING, src.NUMVOTES);

-- Task: Merge Kaggle metadata changes into Silver
CREATE OR REPLACE TASK MOVIE_PROJECT_DB.PUBLIC.task_cdc_silver_kaggle
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '5 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.STREAM_MOVIES_METADATA')
  COMMENT = 'Incrementally merges new/changed Kaggle metadata into Silver layer'
AS
  MERGE INTO MOVIE_PROJECT_DB.SILVER.MOVIES_METADATA_INCREMENTAL tgt
  USING (
    SELECT
      TRY_CAST(ID AS NUMBER) AS MOVIE_ID,
      TITLE,
      TRY_CAST(BUDGET AS NUMBER) AS BUDGET,
      TRY_CAST(REVENUE AS NUMBER) AS REVENUE,
      TRY_CAST(POPULARITY AS FLOAT) AS POPULARITY,
      TRY_CAST(VOTE_AVERAGE AS FLOAT) AS VOTE_AVERAGE,
      TRY_CAST(VOTE_COUNT AS NUMBER) AS VOTE_COUNT,
      GENRES,
      PRODUCTION_COMPANIES,
      TRY_CAST(RUNTIME AS NUMBER) AS RUNTIME,
      TRY_TO_DATE(RELEASE_DATE) AS RELEASE_DATE,
      YEAR(TRY_TO_DATE(RELEASE_DATE)) AS RELEASE_YEAR,
      ORIGINAL_LANGUAGE,
      STATUS,
      IMDB_ID
    FROM MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.STREAM_MOVIES_METADATA
    WHERE TRY_CAST(ID AS NUMBER) IS NOT NULL
      AND TITLE IS NOT NULL
      AND METADATA$ACTION = 'INSERT'
  ) src
  ON tgt.MOVIE_ID = src.MOVIE_ID
  WHEN MATCHED THEN UPDATE SET
    tgt.TITLE = src.TITLE, tgt.BUDGET = src.BUDGET, tgt.REVENUE = src.REVENUE,
    tgt.POPULARITY = src.POPULARITY, tgt.VOTE_AVERAGE = src.VOTE_AVERAGE,
    tgt.VOTE_COUNT = src.VOTE_COUNT, tgt.GENRES = src.GENRES,
    tgt.PRODUCTION_COMPANIES = src.PRODUCTION_COMPANIES, tgt.RUNTIME = src.RUNTIME,
    tgt.RELEASE_DATE = src.RELEASE_DATE, tgt.RELEASE_YEAR = src.RELEASE_YEAR,
    tgt.ORIGINAL_LANGUAGE = src.ORIGINAL_LANGUAGE, tgt.STATUS = src.STATUS,
    tgt.IMDB_ID = src.IMDB_ID, tgt.LAST_UPDATED = CURRENT_TIMESTAMP()
  WHEN NOT MATCHED THEN INSERT (MOVIE_ID, TITLE, BUDGET, REVENUE, POPULARITY, VOTE_AVERAGE, VOTE_COUNT, GENRES, PRODUCTION_COMPANIES, RUNTIME, RELEASE_DATE, RELEASE_YEAR, ORIGINAL_LANGUAGE, STATUS, IMDB_ID)
    VALUES (src.MOVIE_ID, src.TITLE, src.BUDGET, src.REVENUE, src.POPULARITY, src.VOTE_AVERAGE, src.VOTE_COUNT, src.GENRES, src.PRODUCTION_COMPANIES, src.RUNTIME, src.RELEASE_DATE, src.RELEASE_YEAR, src.ORIGINAL_LANGUAGE, src.STATUS, src.IMDB_ID);

-- Task: Merge MovieLens ratings changes into Silver
CREATE OR REPLACE TASK MOVIE_PROJECT_DB.PUBLIC.task_cdc_silver_movielens
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '5 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.STREAM_RATINGS')
  COMMENT = 'Incrementally merges new MovieLens ratings into Silver aggregation'
AS
  MERGE INTO MOVIE_PROJECT_DB.SILVER.MOVIELENS_RATINGS_INCREMENTAL tgt
  USING (
    SELECT
      m.MOVIE_ID,
      m.TITLE,
      m.GENRES,
      AVG(r.RATING) AS AVG_RATING,
      COUNT(r.RATING) AS RATING_COUNT,
      COUNT(DISTINCT r.USER_ID) AS UNIQUE_USERS
    FROM MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.MOVIES m
    JOIN MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.STREAM_RATINGS r ON m.MOVIE_ID = r.MOVIE_ID
    WHERE r.METADATA$ACTION = 'INSERT'
    GROUP BY m.MOVIE_ID, m.TITLE, m.GENRES
    HAVING COUNT(r.RATING) >= 1
  ) src
  ON tgt.MOVIE_ID = src.MOVIE_ID
  WHEN MATCHED THEN UPDATE SET
    tgt.AVG_RATING = (tgt.AVG_RATING * tgt.RATING_COUNT + src.AVG_RATING * src.RATING_COUNT) / (tgt.RATING_COUNT + src.RATING_COUNT),
    tgt.RATING_COUNT = tgt.RATING_COUNT + src.RATING_COUNT,
    tgt.UNIQUE_USERS = tgt.UNIQUE_USERS + src.UNIQUE_USERS,
    tgt.LAST_UPDATED = CURRENT_TIMESTAMP()
  WHEN NOT MATCHED THEN INSERT (MOVIE_ID, TITLE, GENRES, AVG_RATING, RATING_COUNT, UNIQUE_USERS)
    VALUES (src.MOVIE_ID, src.TITLE, src.GENRES, src.AVG_RATING, src.RATING_COUNT, src.UNIQUE_USERS);

-- =============================================================================
-- SECTION 4: CDC AUDIT LOG (tracks every stream consumption)
-- =============================================================================

CREATE TABLE IF NOT EXISTS MOVIE_PROJECT_DB.PUBLIC.CDC_AUDIT_LOG (
    LOG_ID NUMBER AUTOINCREMENT,
    STREAM_NAME VARCHAR,
    TASK_NAME VARCHAR,
    ROWS_INSERTED NUMBER,
    ROWS_UPDATED NUMBER,
    ROWS_DELETED NUMBER,
    EXECUTION_TIME_MS NUMBER,
    EXECUTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- SECTION 5: VERIFY STREAMS
-- =============================================================================
SHOW STREAMS IN DATABASE MOVIE_PROJECT_DB;
