-- =============================================================================
-- GOLD LAYER VIEWS
-- Database: MOVIE_PROJECT_DB | Schema: GOLD
-- Purpose: Pre-aggregated business metrics for dashboard consumption
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS MOVIE_PROJECT_DB.GOLD;

-- -----------------------------------------------------------------------------
-- BUSINESS REQUIREMENT 1: Movie Popularity Analysis
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.TOP_MOVIES_BY_VOTES AS
SELECT TITLE, NUMVOTES, IMDB_RATING, RELEASE_YEAR, GENRES
FROM MOVIE_PROJECT_DB.SILVER.IMDB_MOVIES
ORDER BY NUMVOTES DESC
LIMIT 100;

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.TOP_MOVIES_BY_RATING AS
SELECT TITLE, IMDB_RATING, NUMVOTES, RELEASE_YEAR, GENRES
FROM MOVIE_PROJECT_DB.SILVER.IMDB_MOVIES
ORDER BY IMDB_RATING DESC
LIMIT 100;

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.MOST_POPULAR_BY_YEAR AS
SELECT * FROM (
    SELECT
        TITLE, RELEASE_YEAR, NUMVOTES, IMDB_RATING,
        ROW_NUMBER() OVER (PARTITION BY RELEASE_YEAR ORDER BY NUMVOTES DESC) AS RN
    FROM MOVIE_PROJECT_DB.SILVER.IMDB_MOVIES
)
WHERE RN = 1;

-- -----------------------------------------------------------------------------
-- BUSINESS REQUIREMENT 2: Genre Performance Analysis
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.GENRE_PERFORMANCE AS
SELECT
    g.VALUE:name::STRING AS GENRE,
    COUNT(*) AS TOTAL_MOVIES,
    ROUND(AVG(VOTE_AVERAGE), 2) AS AVG_RATING,
    ROUND(AVG(REVENUE), 0) AS AVG_REVENUE,
    ROUND(AVG(BUDGET), 0) AS AVG_BUDGET,
    ROUND(AVG(REVENUE) - AVG(BUDGET), 0) AS AVG_PROFIT,
    ROUND(AVG(RUNTIME), 1) AS AVG_RUNTIME,
    SUM(VOTE_COUNT) AS TOTAL_VOTES,
    RANK() OVER (ORDER BY SUM(VOTE_COUNT) DESC) AS GENRE_POPULARITY_RANK
FROM MOVIE_PROJECT_DB.SILVER.MOVIES_METADATA,
    LATERAL FLATTEN(INPUT => PARSE_JSON(GENRES)) g
WHERE g.VALUE:name IS NOT NULL
GROUP BY g.VALUE:name::STRING;

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.GENRE_BY_YEAR AS
SELECT
    g.VALUE:name::STRING AS GENRE,
    RELEASE_YEAR,
    COUNT(*) AS MOVIE_COUNT,
    ROUND(AVG(VOTE_AVERAGE), 2) AS AVG_RATING,
    ROUND(AVG(REVENUE), 0) AS AVG_REVENUE
FROM MOVIE_PROJECT_DB.SILVER.MOVIES_METADATA,
    LATERAL FLATTEN(INPUT => PARSE_JSON(GENRES)) g
WHERE g.VALUE:name IS NOT NULL AND RELEASE_YEAR IS NOT NULL
GROUP BY g.VALUE:name::STRING, RELEASE_YEAR;

-- -----------------------------------------------------------------------------
-- BUSINESS REQUIREMENT 3: Movie Financial Performance
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.MOVIE_FINANCIALS AS
SELECT
    MOVIE_ID,
    TITLE,
    BUDGET,
    REVENUE,
    REVENUE - BUDGET AS PROFIT,
    ROUND(((REVENUE - BUDGET) / NULLIF(BUDGET, 0)) * 100, 2) AS ROI,
    ROUND(REVENUE / NULLIF(BUDGET, 0), 2) AS REVENUE_TO_BUDGET_RATIO,
    ROUND(((REVENUE - BUDGET) / NULLIF(REVENUE, 0)) * 100, 2) AS PROFIT_MARGIN,
    RELEASE_YEAR,
    GENRES,
    PRODUCTION_COMPANIES
FROM MOVIE_PROJECT_DB.SILVER.MOVIES_METADATA
WHERE BUDGET > 0 AND REVENUE > 0;

-- -----------------------------------------------------------------------------
-- BUSINESS REQUIREMENT 4: Streaming Catalog Analysis (Netflix)
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.NETFLIX_CONTENT_SUMMARY AS
SELECT
    COUNT(*) AS TOTAL_TITLES,
    SUM(CASE WHEN TYPE = 'Movie' THEN 1 ELSE 0 END) AS MOVIES_COUNT,
    SUM(CASE WHEN TYPE = 'TV Show' THEN 1 ELSE 0 END) AS TV_SHOWS_COUNT
FROM MOVIE_PROJECT_DB.SILVER.NETFLIX_CATALOG;

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.NETFLIX_ADDED_BY_YEAR AS
SELECT
    ADDED_YEAR,
    COUNT(*) AS TITLES_ADDED,
    SUM(CASE WHEN TYPE = 'Movie' THEN 1 ELSE 0 END) AS MOVIES_ADDED,
    SUM(CASE WHEN TYPE = 'TV Show' THEN 1 ELSE 0 END) AS TV_SHOWS_ADDED
FROM MOVIE_PROJECT_DB.SILVER.NETFLIX_CATALOG
WHERE ADDED_YEAR IS NOT NULL
GROUP BY ADDED_YEAR;

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.NETFLIX_BY_COUNTRY AS
SELECT
    TRIM(c.VALUE::STRING) AS COUNTRY,
    COUNT(*) AS TITLE_COUNT
FROM MOVIE_PROJECT_DB.SILVER.NETFLIX_CATALOG,
    LATERAL FLATTEN(INPUT => SPLIT(COUNTRY, ',')) c
WHERE COUNTRY IS NOT NULL
GROUP BY TRIM(c.VALUE::STRING)
ORDER BY TITLE_COUNT DESC;

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.NETFLIX_BY_GENRE AS
SELECT
    TRIM(g.VALUE::STRING) AS GENRE,
    COUNT(*) AS TITLE_COUNT
FROM MOVIE_PROJECT_DB.SILVER.NETFLIX_CATALOG,
    LATERAL FLATTEN(INPUT => SPLIT(GENRE, ',')) g
WHERE GENRE IS NOT NULL
GROUP BY TRIM(g.VALUE::STRING)
ORDER BY TITLE_COUNT DESC;

-- -----------------------------------------------------------------------------
-- BUSINESS REQUIREMENT 5: User Rating Behavior
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.USER_RATING_DISTRIBUTION AS
SELECT
    RATING,
    COUNT(*) AS RATING_COUNT
FROM MOVIE_PROJECT_DB.SILVER.MOVIELENS_USER_RATINGS
GROUP BY RATING
ORDER BY RATING;

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.USER_ACTIVITY AS
SELECT
    USER_ID,
    COUNT(*) AS RATING_COUNT,
    ROUND(AVG(RATING), 2) AS AVG_RATING,
    MIN(RATING_DATE) AS FIRST_RATING,
    MAX(RATING_DATE) AS LAST_RATING
FROM MOVIE_PROJECT_DB.SILVER.MOVIELENS_USER_RATINGS
GROUP BY USER_ID;

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.RATINGS_BY_YEAR AS
SELECT
    RATING_YEAR AS YEAR,
    COUNT(*) AS TOTAL_RATINGS,
    COUNT(DISTINCT USER_ID) AS ACTIVE_USERS,
    ROUND(AVG(RATING), 2) AS AVG_RATING
FROM MOVIE_PROJECT_DB.SILVER.MOVIELENS_USER_RATINGS
WHERE RATING_YEAR IS NOT NULL
GROUP BY RATING_YEAR;

-- -----------------------------------------------------------------------------
-- BUSINESS REQUIREMENT 6: Recommendation Analytics
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.MOVIES_BY_TAG AS
SELECT
    TAG,
    TITLE,
    COUNT(*) AS TAG_COUNT,
    COUNT(DISTINCT USER_ID) AS UNIQUE_USERS
FROM MOVIE_PROJECT_DB.SILVER.MOVIELENS_TAGS
GROUP BY TAG, TITLE;

-- -----------------------------------------------------------------------------
-- BUSINESS REQUIREMENT 7: Cast and Crew Analysis
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.ACTOR_PERFORMANCE AS
SELECT
    PRIMARYNAME,
    COUNT(DISTINCT TCONST) AS MOVIE_COUNT,
    ROUND(AVG(IMDB_RATING), 2) AS AVG_RATING,
    SUM(NUMVOTES) AS TOTAL_VOTES
FROM MOVIE_PROJECT_DB.SILVER.IMDB_CAST_CREW
WHERE CATEGORY IN ('actor', 'actress')
GROUP BY PRIMARYNAME
HAVING COUNT(DISTINCT TCONST) >= 5;

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.DIRECTOR_PERFORMANCE AS
SELECT
    PRIMARYNAME,
    COUNT(DISTINCT TCONST) AS MOVIE_COUNT,
    ROUND(AVG(IMDB_RATING), 2) AS AVG_RATING,
    SUM(NUMVOTES) AS TOTAL_VOTES
FROM MOVIE_PROJECT_DB.SILVER.IMDB_CAST_CREW
WHERE CATEGORY = 'director'
GROUP BY PRIMARYNAME
HAVING COUNT(DISTINCT TCONST) >= 3;

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.ACTOR_DIRECTOR_COMBOS AS
SELECT
    a.PRIMARYNAME AS ACTOR,
    d.PRIMARYNAME AS DIRECTOR,
    COUNT(DISTINCT a.TCONST) AS MOVIES_TOGETHER,
    ROUND(AVG(a.IMDB_RATING), 2) AS AVG_RATING
FROM MOVIE_PROJECT_DB.SILVER.IMDB_CAST_CREW a
JOIN MOVIE_PROJECT_DB.SILVER.IMDB_CAST_CREW d ON a.TCONST = d.TCONST
WHERE a.CATEGORY IN ('actor', 'actress') AND d.CATEGORY = 'director'
GROUP BY a.PRIMARYNAME, d.PRIMARYNAME
HAVING COUNT(DISTINCT a.TCONST) >= 2;

-- -----------------------------------------------------------------------------
-- BUSINESS REQUIREMENT 8: User Engagement Analytics
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.ENGAGEMENT_BY_GENRE AS
SELECT
    TRIM(g.VALUE::STRING) AS GENRE,
    COUNT(*) AS RATING_COUNT,
    COUNT(DISTINCT USER_ID) AS UNIQUE_USERS,
    ROUND(AVG(RATING), 2) AS AVG_RATING
FROM MOVIE_PROJECT_DB.SILVER.MOVIELENS_USER_RATINGS,
    LATERAL FLATTEN(INPUT => SPLIT(GENRES, '|')) g
WHERE GENRES IS NOT NULL
GROUP BY TRIM(g.VALUE::STRING)
ORDER BY RATING_COUNT DESC;

-- -----------------------------------------------------------------------------
-- BUSINESS REQUIREMENT 9: Pipeline Monitoring
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.PIPELINE_HEALTH AS
SELECT 'TITLE_BASICS' AS SOURCE_TABLE, COUNT(*) AS ROW_COUNT,
       SUM(CASE WHEN PRIMARYTITLE IS NULL THEN 1 ELSE 0 END) AS NULL_KEY_FIELD,
       SUM(CASE WHEN STARTYEAR IS NULL THEN 1 ELSE 0 END) AS NULL_SECONDARY_FIELD
FROM MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_BASICS
UNION ALL
SELECT 'TITLE_RATINGS', COUNT(*),
       SUM(CASE WHEN TCONST IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN AVERAGERATING IS NULL THEN 1 ELSE 0 END)
FROM MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_RATINGS
UNION ALL
SELECT 'MOVIES_METADATA', COUNT(*),
       SUM(CASE WHEN TITLE IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CAST(ID AS NUMBER) IS NULL THEN 1 ELSE 0 END)
FROM MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.MOVIES_METADATA
UNION ALL
SELECT 'MOVIELENS_RATINGS', COUNT(*),
       SUM(CASE WHEN USER_ID IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN RATING IS NULL THEN 1 ELSE 0 END)
FROM MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.RATINGS
UNION ALL
SELECT 'NETFLIX', COUNT(*),
       SUM(CASE WHEN TITLE IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TYPE IS NULL THEN 1 ELSE 0 END)
FROM MOVIE_PROJECT_DB.BRONZE_API.NETFLIX
UNION ALL
SELECT 'CREDITS', COUNT(*),
       SUM(CASE WHEN ID IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN CAST_COL IS NULL THEN 1 ELSE 0 END)
FROM MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.CREDITS;

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.PIPELINE_DUPLICATES AS
SELECT 'TITLE_RATINGS' AS SOURCE, COUNT(*) - COUNT(DISTINCT TCONST) AS DUPLICATE_COUNT
FROM MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_RATINGS
UNION ALL
SELECT 'MOVIES_METADATA', COUNT(*) - COUNT(DISTINCT ID)
FROM MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.MOVIES_METADATA
UNION ALL
SELECT 'NETFLIX', COUNT(*) - COUNT(DISTINCT SHOW_ID)
FROM MOVIE_PROJECT_DB.BRONZE_API.NETFLIX;

-- -----------------------------------------------------------------------------
-- ADDITIONAL GOLD VIEWS (to eliminate direct Silver reads from dashboard)
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.IMDB_MOVIES_BY_GENRE AS
SELECT TITLE, IMDB_RATING, NUMVOTES, RELEASE_YEAR, GENRES
FROM MOVIE_PROJECT_DB.SILVER.IMDB_MOVIES;

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.IMDB_MOVIELENS_COMPARISON AS
SELECT i.TITLE, i.IMDB_RATING, m.AVG_RATING AS MOVIELENS_RATING
FROM MOVIE_PROJECT_DB.SILVER.IMDB_MOVIES i
JOIN MOVIE_PROJECT_DB.SILVER.MOVIELENS_MOVIE_RATINGS m ON LOWER(i.TITLE) = LOWER(m.TITLE);

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.MOVIELENS_TOP_RATED AS
SELECT TITLE, ROUND(AVG_RATING, 2) AS AVG_RATING, RATING_COUNT, GENRES
FROM MOVIE_PROJECT_DB.SILVER.MOVIELENS_MOVIE_RATINGS;

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.MOVIELENS_GENRE_LIST AS
SELECT DISTINCT TRIM(g.VALUE::STRING) AS GENRE
FROM MOVIE_PROJECT_DB.SILVER.MOVIELENS_MOVIE_RATINGS,
    LATERAL FLATTEN(INPUT => SPLIT(GENRES, '|')) g
WHERE GENRES IS NOT NULL;

CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.NETFLIX_MATURITY_RATINGS AS
SELECT MATURITY_RATING AS RATING, COUNT(*) AS COUNT
FROM MOVIE_PROJECT_DB.SILVER.NETFLIX_CATALOG
WHERE MATURITY_RATING IS NOT NULL
GROUP BY MATURITY_RATING;

-- =============================================================================
-- FACT & DIMENSION TABLES (Star Schema Layer)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- DIMENSION: DIM_MOVIES
-- Grain: One row per movie
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TABLE MOVIE_PROJECT_DB.GOLD.DIM_MOVIES AS
SELECT
    ROW_NUMBER() OVER (ORDER BY sm.MOVIE_ID) AS MOVIE_SK,
    sm.MOVIE_ID,
    sm.TITLE,
    sm.ORIGINAL_LANGUAGE,
    sm.STATUS,
    sm.RUNTIME,
    sm.RELEASE_DATE,
    sm.RELEASE_YEAR,
    sm.BUDGET,
    sm.REVENUE,
    sm.IMDB_ID,
    im.TCONST,
    im.IMDB_RATING,
    im.NUMVOTES,
    sm.POPULARITY AS TMDB_POPULARITY,
    sm.VOTE_AVERAGE AS TMDB_VOTE_AVERAGE,
    sm.VOTE_COUNT AS TMDB_VOTE_COUNT,
    sm.PRODUCTION_COMPANIES,
    sm.GENRES AS GENRES_JSON
FROM MOVIE_PROJECT_DB.SILVER.MOVIES_METADATA sm
LEFT JOIN MOVIE_PROJECT_DB.SILVER.IMDB_MOVIES im ON sm.IMDB_ID = im.TCONST;

-- -----------------------------------------------------------------------------
-- DIMENSION: DIM_GENRES
-- Grain: One row per genre
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TABLE MOVIE_PROJECT_DB.GOLD.DIM_GENRES AS
SELECT
    ROW_NUMBER() OVER (ORDER BY GENRE) AS GENRE_SK,
    GENRE
FROM (
    SELECT DISTINCT g.VALUE:name::STRING AS GENRE
    FROM MOVIE_PROJECT_DB.SILVER.MOVIES_METADATA,
        LATERAL FLATTEN(INPUT => PARSE_JSON(GENRES)) g
    WHERE g.VALUE:name IS NOT NULL
    UNION
    SELECT DISTINCT TRIM(VALUE::STRING) AS GENRE
    FROM MOVIE_PROJECT_DB.SILVER.IMDB_MOVIES,
        LATERAL FLATTEN(INPUT => SPLIT(GENRES, ','))
    WHERE GENRES IS NOT NULL
)
WHERE GENRE IS NOT NULL AND GENRE != '';

-- -----------------------------------------------------------------------------
-- DIMENSION: DIM_ACTORS
-- Grain: One row per actor/actress
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TABLE MOVIE_PROJECT_DB.GOLD.DIM_ACTORS AS
SELECT
    ROW_NUMBER() OVER (ORDER BY PRIMARYNAME) AS ACTOR_SK,
    NCONST,
    PRIMARYNAME,
    CATEGORY
FROM (
    SELECT DISTINCT NCONST, PRIMARYNAME, CATEGORY
    FROM MOVIE_PROJECT_DB.SILVER.IMDB_CAST_CREW
    WHERE CATEGORY IN ('actor', 'actress')
);

-- -----------------------------------------------------------------------------
-- DIMENSION: DIM_DIRECTORS
-- Grain: One row per director
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TABLE MOVIE_PROJECT_DB.GOLD.DIM_DIRECTORS AS
SELECT
    ROW_NUMBER() OVER (ORDER BY PRIMARYNAME) AS DIRECTOR_SK,
    NCONST,
    PRIMARYNAME
FROM (
    SELECT DISTINCT NCONST, PRIMARYNAME
    FROM MOVIE_PROJECT_DB.SILVER.IMDB_CAST_CREW
    WHERE CATEGORY = 'director'
);

-- -----------------------------------------------------------------------------
-- DIMENSION: DIM_DATE
-- Grain: One row per date (1950 to 2030)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TABLE MOVIE_PROJECT_DB.GOLD.DIM_DATE AS
SELECT
    TO_NUMBER(TO_CHAR(d.DATE_VAL, 'YYYYMMDD')) AS DATE_SK,
    d.DATE_VAL AS FULL_DATE,
    YEAR(d.DATE_VAL) AS YEAR,
    QUARTER(d.DATE_VAL) AS QUARTER,
    MONTH(d.DATE_VAL) AS MONTH,
    MONTHNAME(d.DATE_VAL) AS MONTH_NAME,
    DAY(d.DATE_VAL) AS DAY,
    DAYOFWEEK(d.DATE_VAL) AS DAY_OF_WEEK,
    DAYNAME(d.DATE_VAL) AS DAY_NAME,
    WEEKOFYEAR(d.DATE_VAL) AS WEEK_OF_YEAR
FROM (
    SELECT DATEADD(DAY, SEQ4(), '1950-01-01'::DATE) AS DATE_VAL
    FROM TABLE(GENERATOR(ROWCOUNT => 29220))
) d;

-- -----------------------------------------------------------------------------
-- DIMENSION: DIM_COUNTRIES
-- Grain: One row per country
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TABLE MOVIE_PROJECT_DB.GOLD.DIM_COUNTRIES AS
SELECT
    ROW_NUMBER() OVER (ORDER BY COUNTRY) AS COUNTRY_SK,
    COUNTRY
FROM (
    SELECT DISTINCT TRIM(c.VALUE::STRING) AS COUNTRY
    FROM MOVIE_PROJECT_DB.SILVER.NETFLIX_CATALOG,
        LATERAL FLATTEN(INPUT => SPLIT(COUNTRY, ',')) c
    WHERE COUNTRY IS NOT NULL
)
WHERE COUNTRY IS NOT NULL AND COUNTRY != '';

-- -----------------------------------------------------------------------------
-- FACT: FACT_RATINGS
-- Grain: One row per user-movie rating
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.FACT_RATINGS AS
SELECT
    r.USER_ID,
    r.MOVIE_ID,
    r.RATING,
    r.RATING_DATE,
    r.RATING_YEAR,
    r.RATING_MONTH,
    r.TITLE,
    r.GENRES
FROM MOVIE_PROJECT_DB.SILVER.MOVIELENS_USER_RATINGS r;

-- -----------------------------------------------------------------------------
-- FACT: FACT_MOVIE_FINANCIALS
-- Grain: One row per movie with financial metrics
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.FACT_MOVIE_FINANCIALS AS
SELECT
    dm.MOVIE_SK,
    dm.MOVIE_ID,
    dm.TITLE,
    dm.BUDGET,
    dm.REVENUE,
    dm.REVENUE - dm.BUDGET AS PROFIT,
    CASE WHEN dm.BUDGET > 0 THEN ROUND(((dm.REVENUE - dm.BUDGET) / dm.BUDGET) * 100, 2) ELSE NULL END AS ROI,
    CASE WHEN dm.REVENUE > 0 THEN ROUND(((dm.REVENUE - dm.BUDGET) / dm.REVENUE) * 100, 2) ELSE NULL END AS PROFIT_MARGIN,
    dm.RELEASE_YEAR,
    dm.IMDB_RATING,
    dm.NUMVOTES,
    dm.TMDB_POPULARITY
FROM MOVIE_PROJECT_DB.GOLD.DIM_MOVIES dm
WHERE dm.BUDGET > 0 AND dm.REVENUE > 0;

-- -----------------------------------------------------------------------------
-- FACT: FACT_NETFLIX_CATALOG
-- Grain: One row per Netflix title
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.FACT_NETFLIX_CATALOG AS
SELECT
    SHOW_ID,
    TYPE,
    TITLE,
    DIRECTOR,
    CAST_MEMBERS,
    COUNTRY,
    DATE_ADDED,
    ADDED_YEAR,
    RELEASE_YEAR,
    MATURITY_RATING,
    DURATION,
    GENRE,
    DESCRIPTION
FROM MOVIE_PROJECT_DB.SILVER.NETFLIX_CATALOG;

-- -----------------------------------------------------------------------------
-- FACT: FACT_CAST_PERFORMANCE
-- Grain: One row per actor/director per movie
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.FACT_CAST_PERFORMANCE AS
SELECT
    cc.TCONST,
    cc.NCONST,
    cc.CATEGORY,
    cc.PRIMARYNAME,
    cc.TITLE,
    cc.RELEASE_YEAR,
    cc.IMDB_RATING,
    cc.NUMVOTES
FROM MOVIE_PROJECT_DB.SILVER.IMDB_CAST_CREW cc;

-- -----------------------------------------------------------------------------
-- BRIDGE: BRIDGE_MOVIE_GENRE (many-to-many between movies and genres)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.GOLD.BRIDGE_MOVIE_GENRE AS
SELECT
    dm.MOVIE_SK,
    dm.MOVIE_ID,
    dm.TITLE,
    dg.GENRE_SK,
    dg.GENRE
FROM MOVIE_PROJECT_DB.GOLD.DIM_MOVIES dm,
    LATERAL FLATTEN(INPUT => PARSE_JSON(dm.GENRES_JSON)) g
JOIN MOVIE_PROJECT_DB.GOLD.DIM_GENRES dg ON dg.GENRE = g.VALUE:name::STRING
WHERE dm.GENRES_JSON IS NOT NULL;
MOVIE_PROJECT_DB.GOLD