-- =============================================================================
-- DEAD-LETTER QUEUE (DLQ) SYSTEM
-- Database: MOVIE_PROJECT_DB
-- Purpose: Captures failed/rejected records at every pipeline stage so no data
--          is silently lost. Failed records are quarantined, logged, and can be
--          reprocessed after root cause is fixed.
-- Depends on: alerting_error_handling.sql (notification integration)
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE SCHEMA IF NOT EXISTS MOVIE_PROJECT_DB.DLQ;

-- =============================================================================
-- SECTION 1: DLQ TABLES (one per failure category)
-- =============================================================================

-- 1A. INGESTION DLQ — Files/rows that failed COPY INTO (Snowpipe or batch)
CREATE OR REPLACE TABLE MOVIE_PROJECT_DB.DLQ.INGESTION_FAILURES (
    DLQ_ID NUMBER AUTOINCREMENT,
    SOURCE_STAGE VARCHAR,           -- @stage/path
    FILE_NAME VARCHAR,
    TARGET_TABLE VARCHAR,
    ERROR_CODE VARCHAR,
    ERROR_MESSAGE VARCHAR,
    ERROR_LINE_NUMBER NUMBER,
    ERROR_COLUMN_NAME VARCHAR,
    REJECTED_RECORD VARCHAR(16777216),  -- raw row content
    PIPE_NAME VARCHAR,
    FAILURE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    REPROCESSED BOOLEAN DEFAULT FALSE,
    REPROCESSED_AT TIMESTAMP_NTZ,
    REPROCESS_ATTEMPT NUMBER DEFAULT 0
);

-- 1B. TRANSFORMATION DLQ — Rows that fail Silver/Gold type casting or business rules
CREATE OR REPLACE TABLE MOVIE_PROJECT_DB.DLQ.TRANSFORMATION_FAILURES (
    DLQ_ID NUMBER AUTOINCREMENT,
    SOURCE_TABLE VARCHAR,
    TARGET_TABLE VARCHAR,
    TRANSFORMATION_STEP VARCHAR,    -- e.g. 'TRY_CAST(ID AS NUMBER)', 'JOIN RATINGS'
    FAILURE_REASON VARCHAR,         -- e.g. 'Non-numeric ID', 'NULL primary key'
    REJECTED_RECORD VARIANT,        -- full row as JSON
    PRIMARY_KEY_VALUE VARCHAR,
    FAILURE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    REPROCESSED BOOLEAN DEFAULT FALSE,
    REPROCESSED_AT TIMESTAMP_NTZ
);

-- 1C. CDC DLQ — Stream records that fail during MERGE operations
CREATE OR REPLACE TABLE MOVIE_PROJECT_DB.DLQ.CDC_FAILURES (
    DLQ_ID NUMBER AUTOINCREMENT,
    STREAM_NAME VARCHAR,
    TARGET_TABLE VARCHAR,
    CDC_ACTION VARCHAR,             -- INSERT, UPDATE, DELETE
    ERROR_CODE VARCHAR,
    ERROR_MESSAGE VARCHAR,
    REJECTED_RECORD VARIANT,        -- full stream row as JSON
    PRIMARY_KEY_VALUE VARCHAR,
    FAILURE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RETRY_COUNT NUMBER DEFAULT 0,
    MAX_RETRIES NUMBER DEFAULT 3,
    REPROCESSED BOOLEAN DEFAULT FALSE,
    REPROCESSED_AT TIMESTAMP_NTZ
);

-- 1D. DATA QUALITY DLQ — Rows that fail DQ checks and are quarantined
CREATE OR REPLACE TABLE MOVIE_PROJECT_DB.DLQ.DQ_REJECTS (
    DLQ_ID NUMBER AUTOINCREMENT,
    SOURCE_TABLE VARCHAR,
    TEST_NAME VARCHAR,
    TEST_CATEGORY VARCHAR,          -- COMPLETENESS, UNIQUENESS, RANGE, REFERENTIAL
    FAILURE_REASON VARCHAR,
    REJECTED_RECORD VARIANT,
    PRIMARY_KEY_VALUE VARCHAR,
    FAILURE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED BOOLEAN DEFAULT FALSE,
    RESOLVED_AT TIMESTAMP_NTZ,
    RESOLVED_BY VARCHAR
);

-- =============================================================================
-- SECTION 2: DLQ INGESTION — Capture COPY INTO validation failures
-- Uses VALIDATION_MODE to find bad rows without loading them
-- =============================================================================

-- Procedure: Route failed COPY INTO rows to DLQ
CREATE OR REPLACE PROCEDURE MOVIE_PROJECT_DB.DLQ.capture_copy_errors(
    P_TARGET_TABLE VARCHAR,
    P_STAGE_PATH VARCHAR,
    P_PIPE_NAME VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    -- Query the COPY_HISTORY for recent failures
    INSERT INTO MOVIE_PROJECT_DB.DLQ.INGESTION_FAILURES
        (SOURCE_STAGE, FILE_NAME, TARGET_TABLE, ERROR_CODE, ERROR_MESSAGE,
         ERROR_LINE_NUMBER, ERROR_COLUMN_NAME, PIPE_NAME)
    SELECT
        :P_STAGE_PATH,
        FILE_NAME,
        :P_TARGET_TABLE,
        FIRST_ERROR_CODE::VARCHAR,
        FIRST_ERROR_MESSAGE,
        FIRST_ERROR_LINE_NUMBER,
        FIRST_ERROR_COLUMN_NAME,
        :P_PIPE_NAME
    FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => :P_TARGET_TABLE,
        START_TIME => DATEADD('HOUR', -1, CURRENT_TIMESTAMP())
    ))
    WHERE STATUS = 'LOAD_FAILED' OR STATUS = 'PARTIALLY_LOADED';

    RETURN 'Copy errors captured for ' || :P_TARGET_TABLE;
END;

-- =============================================================================
-- SECTION 3: DLQ TRANSFORMATION — Capture rows failing type casts/rules
-- =============================================================================

-- Procedure: Route Kaggle metadata rows with non-numeric IDs to DLQ
CREATE OR REPLACE PROCEDURE MOVIE_PROJECT_DB.DLQ.quarantine_bad_kaggle_rows()
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    INSERT INTO MOVIE_PROJECT_DB.DLQ.TRANSFORMATION_FAILURES
        (SOURCE_TABLE, TARGET_TABLE, TRANSFORMATION_STEP, FAILURE_REASON,
         REJECTED_RECORD, PRIMARY_KEY_VALUE)
    SELECT
        'BRONZE_API_KAGGLE2.MOVIES_METADATA',
        'SILVER.MOVIES_METADATA',
        'TRY_CAST(ID AS NUMBER)',
        CASE
            WHEN TRY_CAST(ID AS NUMBER) IS NULL AND ID IS NOT NULL THEN 'Non-numeric ID: ' || ID
            WHEN TITLE IS NULL THEN 'NULL title'
            ELSE 'Unknown failure'
        END,
        OBJECT_CONSTRUCT(*),
        COALESCE(ID, 'NULL')
    FROM MOVIE_PROJECT_DB.BRONZE_API_KAGGLE2.MOVIES_METADATA
    WHERE TRY_CAST(ID AS NUMBER) IS NULL OR TITLE IS NULL;

    RETURN 'Quarantined ' || SQLROWCOUNT || ' bad Kaggle rows';
END;

-- Procedure: Route IMDB rows with invalid data to DLQ
CREATE OR REPLACE PROCEDURE MOVIE_PROJECT_DB.DLQ.quarantine_bad_imdb_rows()
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    INSERT INTO MOVIE_PROJECT_DB.DLQ.TRANSFORMATION_FAILURES
        (SOURCE_TABLE, TARGET_TABLE, TRANSFORMATION_STEP, FAILURE_REASON,
         REJECTED_RECORD, PRIMARY_KEY_VALUE)
    SELECT
        'BRONZE_API_IMDB.TITLE_BASICS',
        'SILVER.IMDB_MOVIES',
        'TITLETYPE filter + STARTYEAR NOT NULL',
        CASE
            WHEN TCONST IS NULL THEN 'NULL TCONST'
            WHEN PRIMARYTITLE IS NULL THEN 'NULL title'
            WHEN STARTYEAR IS NULL THEN 'NULL STARTYEAR'
            ELSE 'Filtered by TITLETYPE or NUMVOTES'
        END,
        OBJECT_CONSTRUCT(*),
        COALESCE(TCONST, 'NULL')
    FROM MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_BASICS
    WHERE TCONST IS NULL OR PRIMARYTITLE IS NULL OR STARTYEAR IS NULL;

    RETURN 'Quarantined ' || SQLROWCOUNT || ' bad IMDB rows';
END;

-- =============================================================================
-- SECTION 4: DLQ CDC — Safe MERGE wrapper that catches failures
-- =============================================================================

CREATE OR REPLACE PROCEDURE MOVIE_PROJECT_DB.DLQ.safe_merge_imdb()
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    BEGIN
        MERGE INTO MOVIE_PROJECT_DB.SILVER.IMDB_MOVIES_INCREMENTAL tgt
        USING (
            SELECT tb.TCONST, tb.PRIMARYTITLE AS TITLE, tb.ORIGINALTITLE,
                tb.GENRES, tb.STARTYEAR AS RELEASE_YEAR, tb.RUNTIMEMINUTES AS RUNTIME,
                tr.AVERAGERATING AS IMDB_RATING, tr.NUMVOTES
            FROM MOVIE_PROJECT_DB.BRONZE_API_IMDB.STREAM_TITLE_BASICS tb
            JOIN MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_RATINGS tr ON tb.TCONST = tr.TCONST
            WHERE tb.TITLETYPE = 'movie' AND tb.STARTYEAR IS NOT NULL
                AND tr.NUMVOTES >= 100 AND tb.METADATA$ACTION = 'INSERT'
        ) src ON tgt.TCONST = src.TCONST
        WHEN MATCHED THEN UPDATE SET
            tgt.TITLE = src.TITLE, tgt.GENRES = src.GENRES,
            tgt.RELEASE_YEAR = src.RELEASE_YEAR, tgt.RUNTIME = src.RUNTIME,
            tgt.IMDB_RATING = src.IMDB_RATING, tgt.NUMVOTES = src.NUMVOTES,
            tgt.LAST_UPDATED = CURRENT_TIMESTAMP()
        WHEN NOT MATCHED THEN INSERT (TCONST, TITLE, ORIGINALTITLE, GENRES, RELEASE_YEAR, RUNTIME, IMDB_RATING, NUMVOTES)
            VALUES (src.TCONST, src.TITLE, src.ORIGINALTITLE, src.GENRES, src.RELEASE_YEAR, src.RUNTIME, src.IMDB_RATING, src.NUMVOTES);

        RETURN 'MERGE SUCCESS';
    EXCEPTION
        WHEN OTHER THEN
            INSERT INTO MOVIE_PROJECT_DB.DLQ.CDC_FAILURES
                (STREAM_NAME, TARGET_TABLE, CDC_ACTION, ERROR_CODE, ERROR_MESSAGE)
            VALUES
                ('STREAM_TITLE_BASICS', 'SILVER.IMDB_MOVIES_INCREMENTAL', 'MERGE',
                 SQLCODE::VARCHAR, SQLERRM);
            RETURN 'MERGE FAILED - routed to DLQ: ' || SQLERRM;
    END;
END;

-- =============================================================================
-- SECTION 5: DLQ DATA QUALITY — Quarantine rows failing DQ checks
-- =============================================================================

CREATE OR REPLACE PROCEDURE MOVIE_PROJECT_DB.DLQ.quarantine_dq_failures()
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    -- Quarantine MovieLens ratings with orphan MOVIE_IDs
    INSERT INTO MOVIE_PROJECT_DB.DLQ.DQ_REJECTS
        (SOURCE_TABLE, TEST_NAME, TEST_CATEGORY, FAILURE_REASON,
         REJECTED_RECORD, PRIMARY_KEY_VALUE)
    SELECT
        'BRONZE_API_MOVIE_LENS.RATINGS',
        'referential_integrity',
        'REFERENTIAL',
        'MOVIE_ID ' || r.MOVIE_ID::VARCHAR || ' does not exist in MOVIES table',
        OBJECT_CONSTRUCT('USER_ID', r.USER_ID, 'MOVIE_ID', r.MOVIE_ID, 'RATING', r.RATING, 'TIMESTAMP', r.RATING_TIMESTAMP),
        r.USER_ID::VARCHAR || ':' || r.MOVIE_ID::VARCHAR
    FROM MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.RATINGS r
    LEFT JOIN MOVIE_PROJECT_DB.BRONZE_API_MOVIE_LENS.MOVIES m ON r.MOVIE_ID = m.MOVIE_ID
    WHERE m.MOVIE_ID IS NULL;

    -- Quarantine IMDB ratings outside valid range
    INSERT INTO MOVIE_PROJECT_DB.DLQ.DQ_REJECTS
        (SOURCE_TABLE, TEST_NAME, TEST_CATEGORY, FAILURE_REASON,
         REJECTED_RECORD, PRIMARY_KEY_VALUE)
    SELECT
        'BRONZE_API_IMDB.TITLE_RATINGS',
        'range_check',
        'RANGE',
        'AVERAGERATING ' || AVERAGERATING::VARCHAR || ' outside valid range 1.0-10.0',
        OBJECT_CONSTRUCT('TCONST', TCONST, 'AVERAGERATING', AVERAGERATING, 'NUMVOTES', NUMVOTES),
        TCONST
    FROM MOVIE_PROJECT_DB.BRONZE_API_IMDB.TITLE_RATINGS
    WHERE AVERAGERATING < 1.0 OR AVERAGERATING > 10.0;

    RETURN 'DQ rejects quarantined';
END;

-- =============================================================================
-- SECTION 6: DLQ REPROCESSING — Retry failed records after fix
-- =============================================================================

CREATE OR REPLACE PROCEDURE MOVIE_PROJECT_DB.DLQ.reprocess_ingestion_failures(
    P_TARGET_TABLE VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    -- Mark as reprocessed (actual reprocessing would re-run COPY with corrected files)
    UPDATE MOVIE_PROJECT_DB.DLQ.INGESTION_FAILURES
    SET REPROCESSED = TRUE,
        REPROCESSED_AT = CURRENT_TIMESTAMP(),
        REPROCESS_ATTEMPT = REPROCESS_ATTEMPT + 1
    WHERE TARGET_TABLE = :P_TARGET_TABLE
      AND REPROCESSED = FALSE
      AND REPROCESS_ATTEMPT < 3;

    RETURN 'Marked ' || SQLROWCOUNT || ' records for reprocessing';
END;

CREATE OR REPLACE PROCEDURE MOVIE_PROJECT_DB.DLQ.reprocess_cdc_failures()
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    UPDATE MOVIE_PROJECT_DB.DLQ.CDC_FAILURES
    SET RETRY_COUNT = RETRY_COUNT + 1,
        REPROCESSED = CASE WHEN RETRY_COUNT + 1 >= MAX_RETRIES THEN TRUE ELSE FALSE END,
        REPROCESSED_AT = CURRENT_TIMESTAMP()
    WHERE REPROCESSED = FALSE AND RETRY_COUNT < MAX_RETRIES;

    RETURN 'Retried ' || SQLROWCOUNT || ' CDC failures';
END;

-- =============================================================================
-- SECTION 7: DLQ MONITORING VIEWS
-- =============================================================================

-- Summary dashboard
CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.DLQ.DLQ_SUMMARY AS
SELECT
    'INGESTION' AS DLQ_CATEGORY,
    COUNT(*) AS TOTAL_FAILURES,
    COUNT_IF(REPROCESSED = FALSE) AS PENDING,
    COUNT_IF(REPROCESSED = TRUE) AS RESOLVED,
    MAX(FAILURE_TIMESTAMP) AS LAST_FAILURE
FROM MOVIE_PROJECT_DB.DLQ.INGESTION_FAILURES
UNION ALL
SELECT 'TRANSFORMATION', COUNT(*), COUNT_IF(REPROCESSED = FALSE), COUNT_IF(REPROCESSED = TRUE), MAX(FAILURE_TIMESTAMP)
FROM MOVIE_PROJECT_DB.DLQ.TRANSFORMATION_FAILURES
UNION ALL
SELECT 'CDC', COUNT(*), COUNT_IF(REPROCESSED = FALSE), COUNT_IF(REPROCESSED = TRUE), MAX(FAILURE_TIMESTAMP)
FROM MOVIE_PROJECT_DB.DLQ.CDC_FAILURES
UNION ALL
SELECT 'DATA_QUALITY', COUNT(*), COUNT_IF(RESOLVED = FALSE), COUNT_IF(RESOLVED = TRUE), MAX(FAILURE_TIMESTAMP)
FROM MOVIE_PROJECT_DB.DLQ.DQ_REJECTS;

-- Recent failures (for alerting)
CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.DLQ.RECENT_FAILURES AS
SELECT DLQ_ID, 'INGESTION' AS CATEGORY, TARGET_TABLE AS AFFECTED_TABLE,
    ERROR_MESSAGE AS REASON, FAILURE_TIMESTAMP, REPROCESSED
FROM MOVIE_PROJECT_DB.DLQ.INGESTION_FAILURES
WHERE FAILURE_TIMESTAMP >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
UNION ALL
SELECT DLQ_ID, 'TRANSFORMATION', TARGET_TABLE, FAILURE_REASON, FAILURE_TIMESTAMP, REPROCESSED
FROM MOVIE_PROJECT_DB.DLQ.TRANSFORMATION_FAILURES
WHERE FAILURE_TIMESTAMP >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
UNION ALL
SELECT DLQ_ID, 'CDC', TARGET_TABLE, ERROR_MESSAGE, FAILURE_TIMESTAMP, REPROCESSED
FROM MOVIE_PROJECT_DB.DLQ.CDC_FAILURES
WHERE FAILURE_TIMESTAMP >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
UNION ALL
SELECT DLQ_ID, 'DATA_QUALITY', SOURCE_TABLE, FAILURE_REASON, FAILURE_TIMESTAMP, RESOLVED
FROM MOVIE_PROJECT_DB.DLQ.DQ_REJECTS
WHERE FAILURE_TIMESTAMP >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
ORDER BY FAILURE_TIMESTAMP DESC;

-- Aging report (failures older than 24h that haven't been resolved)
CREATE OR REPLACE VIEW MOVIE_PROJECT_DB.DLQ.AGING_FAILURES AS
SELECT
    'INGESTION' AS CATEGORY, DLQ_ID, TARGET_TABLE,
    FAILURE_TIMESTAMP, REPROCESS_ATTEMPT,
    DATEDIFF('HOUR', FAILURE_TIMESTAMP, CURRENT_TIMESTAMP()) AS HOURS_OLD
FROM MOVIE_PROJECT_DB.DLQ.INGESTION_FAILURES
WHERE REPROCESSED = FALSE AND FAILURE_TIMESTAMP < DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
UNION ALL
SELECT 'CDC', DLQ_ID, TARGET_TABLE, FAILURE_TIMESTAMP, RETRY_COUNT,
    DATEDIFF('HOUR', FAILURE_TIMESTAMP, CURRENT_TIMESTAMP())
FROM MOVIE_PROJECT_DB.DLQ.CDC_FAILURES
WHERE REPROCESSED = FALSE AND FAILURE_TIMESTAMP < DATEADD('HOUR', -24, CURRENT_TIMESTAMP());

-- =============================================================================
-- SECTION 8: ALERT — DLQ THRESHOLD BREACH
-- Fires when unresolved DLQ records exceed threshold
-- =============================================================================

CREATE OR REPLACE ALERT MOVIE_PROJECT_DB.DLQ.alert_dlq_threshold
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '30 MINUTE'
  IF (EXISTS (
    SELECT 1 FROM (
        SELECT COUNT_IF(REPROCESSED = FALSE) AS PENDING FROM MOVIE_PROJECT_DB.DLQ.INGESTION_FAILURES
        UNION ALL SELECT COUNT_IF(REPROCESSED = FALSE) FROM MOVIE_PROJECT_DB.DLQ.CDC_FAILURES
        UNION ALL SELECT COUNT_IF(REPROCESSED = FALSE) FROM MOVIE_PROJECT_DB.DLQ.TRANSFORMATION_FAILURES
        UNION ALL SELECT COUNT_IF(RESOLVED = FALSE) FROM MOVIE_PROJECT_DB.DLQ.DQ_REJECTS
    ) WHERE PENDING > 10
  ))
  THEN
    CALL SYSTEM$SEND_EMAIL(
      'movie_pipeline_email_alerts',
      'ashishmachcha7@gmail.com',
      'ALERT: DLQ Threshold Exceeded',
      'More than 10 unresolved records in Dead-Letter Queue. Check: SELECT * FROM MOVIE_PROJECT_DB.DLQ.DLQ_SUMMARY;'
    );

-- =============================================================================
-- SECTION 9: SCHEDULED DLQ PROCESSING TASK
-- =============================================================================

CREATE OR REPLACE TASK MOVIE_PROJECT_DB.DLQ.task_process_dlq
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '60 MINUTE'
  COMMENT = 'Periodic DLQ processing: quarantine bad rows and retry CDC failures'
AS
BEGIN
    CALL MOVIE_PROJECT_DB.DLQ.quarantine_bad_kaggle_rows();
    CALL MOVIE_PROJECT_DB.DLQ.quarantine_bad_imdb_rows();
    CALL MOVIE_PROJECT_DB.DLQ.quarantine_dq_failures();
    CALL MOVIE_PROJECT_DB.DLQ.reprocess_cdc_failures();
END;

-- =============================================================================
-- VERIFY
-- =============================================================================
SHOW TABLES IN SCHEMA MOVIE_PROJECT_DB.DLQ;
